Release/step1
wotjd243/ddd-project pull request #11
Opened 2019-04-30 06:29 UTC by kjc3590

Release/step1 1주차 도메인 작업 및 테스트 코드 작성

2019-05-02 01:33 UTC, wotjd243 requested changes
짧은 시간에 테스트 코드를 포함한 많은 코드를 작성해주셨어요. 👍 
커밋 메시지를 통해 팀원들 간의 협업도 원활히 된 것을 확인할 수 있었습니다.
IntelliJ IDEA의 코드 자동 정렬 기능(⌥⌘L, Ctrl+Alt+L)을 사용하면 더 깔끔한 코드를 볼 수 있을 거예요.
피드백 남겼으니 확인하고 개선할 부분 있으면 반영해 보세요.
코드 개선 시, 모델링도 함께 업데이트되어야 하는 점 잊지 마세요.

2019-05-02 01:33 UTC, wotjd243 commented on README.md
> +‘미션 포인트’를 100점 모으면 문제를 풀 수 있는 총알을 하나 얻는다.
문제와 미션이 같은 뜻이라면 통일된 용어를, 다른 뜻이라면 용어 사전에 따로 정리하는 것이 좋아 보입니다.

2019-05-02 01:33 UTC, wotjd243 commented on README.md
> +‘보물’을 등록하면 QR코드, 좌표, 상세주소, 러닝타임을 생성한다.
좌표와 상세주소, 러닝 타임은 무작위 생성인가요?

2019-05-02 01:33 UTC, wotjd243 commented on README.md
> +  풀어야하는 ‘미션’의 가지수는 ‘러닝 타임’에 길이에 따라 결정된다.
러닝 타임의 길이에 따라 미션의 수가 어떻게 정해지는지 정리가 필요해 보입니다.

2019-05-02 01:33 UTC, wotjd243 commented on README.md
> +보물 / treasure / 헌터 문제를 풀면 얻게 되는 보상
보물은 보물이 위치한 좌표에 직접 가야 획득할 수 있나요?

2019-05-02 01:33 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/findbyhint/hint/domain/Hint.java
> +    // TODO (2) 힌트를 풀면 해당힌트가 가지고 있는 반지름을 토대로  원의 면적을 보여준다.
TODO 리스트는 요구 사항 혹은 모델링으로 정리가 필요해 보입니다.

2019-05-02 01:33 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/findbyhint/hint/domain/Hint.java
> +    // Trasure 클래스 TargetPoint 메서드 로 좌표값을 구해서 거기서 부터 원의 면적값과 반지름값을 구현한다.
요구 사항 혹은 모델링으로 정리가 필요해 보입니다.

2019-05-02 01:33 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/findbyhint/hint/domain/HintInventory.java
> +    private Long inventoryNum;     /* autoIncrement PK 값*/
`inventoryNum`이 `Hunter`에 종속적인 id라면 `Hunter` ENTITY에 직접 참조로 속하는 것이 좋아 보이고, `Hunter`에도 `Hint`에도 종속적인 것이 아니라면 별도의 AGGREGATE로 다루는 것이 좋지 않을까요?

2019-05-02 01:33 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/findbyhint/hunter/domain/Hunter.java
> +    // TODO (5) hunterPoint의 최대값은 99999점이고 증가 최대치는 100점이다.
요구 사항 혹은 모델링으로 정리가 필요해 보입니다.

2019-05-02 01:33 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/findbyhint/hunter/domain/HunterPictureName.java
> +    Check check = new Check();
유틸리티 클래스는 직접 생성을 통해 사용하는 것보다 정적 메서드를 가지도록 만드는 것은 어떨까요? Apache Commons의 `StringUtils` 클래스를 참고하면 좋을 것 같아요.

2019-05-02 01:33 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/findbyhint/mission/domain/Mission.java
> +    private Treasure Treasure;
AGGREGATE ROOT인 `Treasure`에 `Mission`이 속하도록 만드는 것이 어떨까요? Treasure AGGREGATE에 속한 인스턴스에 대한 접근은 AGGREGATE ROOT인 `Treasure`를 통해서 접근하도록 구현하여야 합니다. 만약 `Mission`이 여러 `Treasure`에서 재사용 될 수 있다면 별도의 AGGREGATE로 분리하는 것도 좋아 보입니다.

2019-05-02 01:33 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/findbyhint/mission/domain/MissionLevel.java
> +public class MissionLevel {
`MissionLevel`은 Enum으로 관리하는 것은 어떨까요? 아래의 글을 참고해보세요.
http://woowabros.github.io/tools/2017/07/10/java-enum-uses.html

2019-05-02 01:33 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/findbyhint/treasure/domain/RunningTime.java
> +    // 공식 :  1주일에 개의 문제  7일당 5문제
요구 사항 혹은 모델링으로 정리가 필요해 보입니다.

2019-05-02 01:33 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/findbyhint/treasure/domain/RunningTime.java
> +        HashMap<String,LocalDate> valueNMap = new HashMap<String,LocalDate>();
Map은 어떤 의도로 사용되었을까요? 값 검증을 위한 용도면 Map이 아니어도 될 것 같습니다.

2019-05-11 09:48 UTC, wotjd243 approved these changes
리뷰 코멘트가 많았음에도 많은 노력을 기울여 주셨어요. 💯 
하지만 아직 불필요한 공백 라인과 일관성 없는 코딩 스타일이 보이네요.
코딩 스타일은 아래의 'Google Java Style Guide' 문서를 참고하면 좋을 것 같아요.
https://google.github.io/styleguide/javaguide.html
상세한 모델링 및 잔존하고 있는 TODO 리스트, 필요하지 않는 주석은 제거 부탁드려요.
step2에 해당하는 내용은 따로 코멘트하지 않았으며, 몇 가지 생각거리는 따로 남겨두었으니 의논해보세요.
빠른 진행을 위해 Merge 하겠습니다!

2019-05-11 09:48 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/findbyhint/mission/domain/MissionRepository.java
> +    Optional<Mission> findById(final MissionLevel level);
`findById()`보다는 `findByMissionLevel()`라는 메서드명이 맞지 않을까요? Mission ENTITY의 식별자는 `missionKey`를 쓰고 있네요.

2019-05-11 09:48 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/findbyhint/mission/domain/MissionLevel.java
> +
공백 라인을 의미 있게 사용하는 것이 좋아 보이며, 문맥을 분리하는 부분에 사용하는 것이 좋습니다. 과도한 공백은 다른 개발자에게 의문을 줄 수 있습니다.

2019-05-11 09:48 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/findbyhint/mission/domain/MissionPoint.java
> +    }*/
프로그래밍을 하다 보면 다음과 같은 느낌이 들어 코드를 삭제하지 않고 주석 처리하는 경우가 있는데요.

- 이 코드가 지금은 사용하지 않지만 언젠가 사용할 수 있을 것 같다.
- 이 코드를 내가 정말 힘들게 구현해서 삭제하기 아깝다.
- 분명 사용하지 않는 코드로 파악되지만 내가 구현한 코드가 아니라 함부로 삭제하기 힘들다.

과거에는 Subversion과 Git 같은 형상관리 툴을 사용하지 않았고, 코드를 참고할만한 곳이 많지 않았기 때문에 주석을 통해 유지하는 것이 의미가 있었을 거예요. 하지만 최근 개발 환경은 형상관리 툴을 사용하는 것이 일반적이 되어 이전에 구현한 코드를 손쉽게 원복 할 수 있게 되었어요. 오히려 지금은 코드를 얼마나 깔끔하고 가독성이 좋은 코드로 유지하는지가 더 중요하지 않을까요? 현시점에 굳이 필요 없다고 생각하는 코드가 있다면 아까운 마음을 버리고 가차 없이 삭제해보세요.

2019-05-11 09:48 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/findbyhint/mission/domain/MissionPoint.java
> +        if(point < 0 || point > 100) {
매직넘버란 코드 안에 작성된 구체적인 숫자 혹은 문자열을 말합니다. 그리고 매직 넘버의 단점은 아래와 같습니다.

- 의미를 이해하기 어렵다.
- 복수의 장소에서 사용된다면 변경하기 힘들다.

그런 매직넘버는 의미를 나타낼 수 있는 상수로 치환하여 코드의 가독성을 높여보는 것은 어떨까요?

2019-05-11 09:48 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/findbyhint/treasure/domain/RunningTime.java
> +            check =false;
바로 아래에서 예외가 발생하는데 `check`의 값을 변경하는 것이 의미가 있는지 궁금하네요. `check`의 값을 변경하는 의미가 없다면 `check`는 불필요한 지역 변수가 될 수도 있겠어요.

2019-05-11 09:48 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/findbyhint/util/check/DateObject.java
> +        localDateTime = LocalDateTime.now();
위험한 코드라는 생각이 들어요. `now()`가 3번 호출되는데 3번 모두 똑같은 시간이라는 보장이 있을까요? `LocalDateTime .now()`를 1번만 호출하고 `toLocalDate()`와 `toLocalTime()`을 사용하는 것은 어떨까요?

2019-05-11 09:48 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/findbyhint/treasure/domain/RunningTime.java
> +        if(!((startDate.isAfter(today.getDate()) || startDate.isEqual(today.getDate())) && endDate.isAfter(today.getDate())  && endDate.isAfter(startDate))){
읽기 어려운 코드라는 생각이 들어요. 아래의 단계를 따르면 가독성이 올라가지 않을까요?

1. `today.getDate()`의 결과 값은 지역 변수에 저장한다.
2. "보물이 생성될 때 러닝타임의 시작일과 종료일은 생성 시간보다 같거나 늦다."에 해당하는 메서드를 분리한다.
3. "같거나 늦다."에 해당하는 메서드를 분리한다.
4. "시작일은 종료일보다 빠르다."에 해당하는 메서드를 분리한다.

2019-05-11 09:48 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/findbyhint/treasure/domain/TargetPoint.java
> +    private final String distinguish;
`TargetPoint`가 진짜인지 가짜인지는 꼭 String이어야 할까요? Enum 일 수도, boolean 일 수도 있을 것 같아요.

2019-05-11 09:48 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/findbyhint/treasure/domain/Treasure.java
> +    private String runningStatus;
"보물의 상태는 대기, 진행, 완료로 이루어져 있다."에 따르면 Enum으로 관리하는 것이 좋아 보여요. `Treasure`가 AGGREGATE ROOT임에도 많은 기능을 가지고 있지 않네요. 보물의 상태를 변경하는 기능 등을 구현해보면 어떨까요?

2019-05-11 09:48 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/findbyhint/treasure/domain/TargetPoint.java
> +    private final Double hardness;
지구 위의 위치를 나타내는 좌표축 중에서 세로로 된 것을 뜻하는 경도는 `longitude`라고 해요.

2019-05-11 09:48 UTC, merged

2019-05-12 01:23 UTC, doyoung0205 commented on src/main/java/io/github/wotjd243/findbyhint/util/check/DateObject.java
> +        localDateTime = LocalDateTime.now();
```
    private  DateObject() {
        final LocalDateTime localDateTime = LocalDateTime.now();
        date = localDateTime.toLocalDate();
        time = localDateTime.toLocalTime();
        this.localDateTime = localDateTime;
    }

```

넵 요렇게 수정하니까 3개의 변수 모두다 똑같은 시간을 갖게 되는것같아요 감사합니당

2019-05-12 01:27 UTC, doyoung0205 commented on src/main/java/io/github/wotjd243/findbyhint/treasure/domain/RunningTime.java
> +        if(!((startDate.isAfter(today.getDate()) || startDate.isEqual(today.getDate())) && endDate.isAfter(today.getDate())  && endDate.isAfter(startDate))){
메소드로 분리한다는것은 유효성 검사 부분을 validation메소드 밖에 따로 만드는것을 의미하나욥?

2019-05-12 01:29 UTC, doyoung0205 commented on src/main/java/io/github/wotjd243/findbyhint/treasure/domain/TargetPoint.java
> +    private final String distinguish;
Enum이 무슨뜻인지 알기 쉬운것같아요
```
@Getter
public enum Distinguish {

    FAKE("0"), REAL("1");

    private final String destines;

    Distinguish(String destines) { this.destines = destines; }
}


```

2019-05-12 01:31 UTC, doyoung0205 commented on src/main/java/io/github/wotjd243/findbyhint/treasure/domain/Treasure.java
> +    private String runningStatus;
Enum으로 수정했습니답 이렇게 하는게 맞나욥?
```
@Getter
public enum EventStatus {

    WAIT("0","대기"), ACTIVE("1","진행"), CLOSE("-1","종료");

    private final String statusValue;
    private final String statusName;

    EventStatus(String statusValue, String statusName) {
        this.statusValue = statusValue;
        this.statusName = statusName;
    }
}
```

2019-05-12 01:40 UTC, doyoung0205 commented on src/main/java/io/github/wotjd243/findbyhint/treasure/domain/Treasure.java
> +    private String runningStatus;
보물의 상태를 변경하는 기능 등을 구현해보면 어떨까요? 
->현재 보물의 상태, 러닝타임, 이름 을 합쳐서 이벤트라는 VO를 만들었습니다.
그러면 이벤트라는 VO 안에서 상태를 변경하는 메소드를 먼저 만들고
이벤트 메소드(보물의 상태를 변경하는 메소드)를 사용하는 메소드를 보물에서 다시 리팩토링 하는게 맞는거죠?
그렇다면 혹시 엔티티안에  VO가있고 또 그안에 두번째VO가 있다면 두번쨰 VO에 관한 메소드는 
엔티티, 첫번쨰 VO, 두번째 VO 에 전부 존재하게 되는건가요?
아니면 첫번쨰 VO에서 두번쨰 VO를 가져다 쓸수 있도록 getter메소드(Proteced)를  구현하게 되는건가요?

-> 보물의 상태를 변경하는 기능은 따로 엔티티에서 만들필요 없이 Repository에서 만들어도 되는건가요?, 객체가 불변해야한다는 것 떄문에 헷갈려요..

2019-05-12 05:36 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/findbyhint/treasure/domain/RunningTime.java
> +        if(!((startDate.isAfter(today.getDate()) || startDate.isEqual(today.getDate())) && endDate.isAfter(today.getDate())  && endDate.isAfter(startDate))){
네, 맞습니다! `dateValidation()`가 너무 많은 기능을 가지고 있어 읽기 어려운 코드가 된 것 같아요.

2019-05-12 05:38 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/findbyhint/treasure/domain/TargetPoint.java
> +    private final String distinguish;
`Distinguish` 내부에 굳이 상태 값이 필요한 이유가 있을까요?

2019-05-12 05:41 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/findbyhint/treasure/domain/Treasure.java
> +    private String runningStatus;
`Treasure`의 경우 ENTITY이며, VALUE OBJECT와 달리 내부의 상태 값이 바뀔 수 있어요. 말씀하신 불변은 VALUE OBJECT에 해당합니다.

2019-05-12 05:48 UTC, doyoung0205 commented on src/main/java/io/github/wotjd243/findbyhint/treasure/domain/TargetPoint.java
> +    private final String distinguish;
단지 진짜, 가짜의 값이 온다면  true, fasle  만으로도 충반할 것 같다는 말씀이신거군욥

2019-05-12 05:52 UTC, doyoung0205 commented on src/main/java/io/github/wotjd243/findbyhint/treasure/domain/Treasure.java
> +    private String runningStatus;
RunningTime , name ,RunningStatus를 하나의 다음과같이 Event 로 만들고 

```
public class Event {

    // 이벤트 상태
    @Column(nullable = false)
    private EventStatus status;

    //이벤트 기간
    private EventPeriod eventPeriod;

    // 이벤트 이름
    @Column(nullable = false)
    private String name;
}
```

보물의 상태는 다음과 같이 정의했습니다.

```
public enum EventStatus {

    WAIT("0","대기"), ACTIVE("1","진행"), CLOSE("-1","종료");

    private final String statusValue;
    private final String statusName;

    EventStatus(String statusValue, String statusName) {
        this.statusValue = statusValue;
        this.statusName = statusName;
    }
}
```

이렇게 되면 VO가 되는것 같은데 VO가 불변이여야 하는 이유가 잘 이해 되지 않습니다...ㅜ_ㅜ

2019-05-12 05:56 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/findbyhint/treasure/domain/TargetPoint.java
> +    private final String distinguish;
아래의 코드는 어떨까요?

```
public enum Distinguish {
    FAKE, REAL
}
```

2019-05-12 05:58 UTC, doyoung0205 commented on src/main/java/io/github/wotjd243/findbyhint/treasure/domain/TargetPoint.java
> +    private final String distinguish;
이렇게 작성하면 DB에는 어떻게 저장되는건가요??

2019-05-12 07:08 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/findbyhint/treasure/domain/TargetPoint.java
> +    private final String distinguish;
`@Enumerated`에 대해 찾아보시면 좋을 것 같습니다.

2019-05-12 07:11 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/findbyhint/treasure/domain/Treasure.java
> +    private String runningStatus;
VALUE OBJECT가 불변이라면 VALUE OBJECT를 어디에 어떤 방식으로 노출시키더라도 예상하지 못한 부작용을 막을 수 있어요. `Money(10_000)`와 `Money(20_000)`는 같은 객체라고 볼 수 있을까요?

2019-05-12 12:36 UTC, ppiyo5 commented on src/main/java/io/github/wotjd243/findbyhint/mission/domain/MissionPoint.java
> +        if(point < 0 || point > 100) {
private static final int MINIMUM_POINT = 0;
    private static final int MAXIMUM_POINT = 100;

    //유효성 검사
    private void validate(final int point) {
        if(point < MINIMUM_POINT || point > MAXIMUM_POINT) {
            throw new IllegalArgumentException();
        }
    }

이런식으로 변경하면 될까요?

2019-05-12 12:37 UTC, ppiyo5 commented on src/main/java/io/github/wotjd243/findbyhint/mission/domain/MissionRepository.java
> +    Optional<Mission> findById(final MissionLevel level);
missionKey로 사용하는 것으로 변경했는데 바꾸지 않았네요. 수정하겠습니다!

2019-05-13 13:38 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/findbyhint/mission/domain/MissionPoint.java
> +        if(point < 0 || point > 100) {
네, 맞습니다. 👍