feat(Item): create requirements and Item class
wotjd243/ddd-project pull request #12
Opened 2019-04-30 09:06 UTC by brainbackdoor

2019-05-02 08:43 UTC, wotjd243 requested changes
테스트 코드 작성과 적절한 VALUE OBJECT 사용이 좋았습니다. 👍 
피드백 남겼으니 확인하고 개선할 부분 있으면 반영해 보세요.
코드 개선 시, 모델링도 함께 업데이트되어야 하는 점 잊지 마세요.

2019-05-02 08:43 UTC, wotjd243 commented on README.md
> +    - [ ]  eBay에 물품을 등록하여 판매하는 사람
"eBay에 물품을 등록하여 판매하는 사람"은 eBay에 실제 물품을 등록하는 것인가요? 아니면 eBay에 등록된 물품을 파는 것인가요?

2019-05-02 08:43 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/support/ecommerce/product/ItemRepository.java
> +        return items.stream().filter(item -> item.match(keywords)).collect(Collectors.toList());
"한 개 이상의 단어로 이루어진 검색 단어. 검색어를 이용해 상품정보를 가져온다. 최소 3글자 이상을 사용한다."에 대한 값 검증이 있으면 좋을 것 같아요.

2019-05-02 08:43 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/support/ecommerce/product/ItemRepository.java
> +public class ItemRepository {
REPOSITORY는 AGGREGATE 단위로 들고 오도록 구현하는 것이 불완전한 AGGREGATE를 들고 오는 것을 방지할 수 있습니다.

2019-05-02 08:43 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/ecommerce/product/domain/Item.java
> +public class Item {
설계의 "Item은 고유한 ID를 갖는다."가 구현되지 않았습니다. 설계 또는 구현을 바꿀 필요가 있어 보여요.

2019-05-02 08:43 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/ecommerce/product/domain/Dollar.java
> +public class Dollar {
VALUE OBJECT 👍

2019-05-02 08:43 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/ecommerce/product/domain/Product.java
> +        return items;
`items`에 대한 주솟값을 그대로 넘겨주게 되면 외부에 의한 변조가 일어나 `Product` AGGREGATE를 해칠 수 있습니다. 새로운 리스트 컬렉션에 담아 외부에 의한 변조를 막는 것은 어떨까요?

2019-05-02 08:43 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/ecommerce/product/domain/Item.java
> +    enum SellingState {
Enum 👍

2019-05-02 08:43 UTC, wotjd243 commented on src/test/java/io/github/wotjd243/ecommerce/product/application/ItemServiceTest.java
> +        assertThat(items.get(0).isSamePrice(25.0)).isTrue();
테스트 명과 테스트 코드가 매칭될 수 있게 연관 지어 작성하는 것은 어떨까요?

2019-05-02 08:43 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/ecommerce/user/domain/Seller.java
> +    public void registerGoods(Product product, Item item) {
`Seller` AGGREGATE에 `Product` AGGREGATE를 인자로 넘길 경우, `Product` AGGREGATE가 오용될 소지가 있습니다. SERVICE를 이용해보는 것이 어떨까요?

2019-05-11 15:12 UTC, wotjd243 approved these changes
팀원들 간의 코드 리뷰는 저도 항상 잘 보고 있습니다. 👍 
코틀린 데이터 클래스 사용이 굉장히 인상적입니다.
하지만 바이너리 파일이 Git으로 관리되는 점은 수정이 필요해 보여요.
Git으로 프로젝트를 관리할 때 Git으로 굳이 관리할 필요가 없는 특정 파일들이 있어요.
자동으로 생성되는 로그 파일, 빌드 할 때 생기는 컴파일된 파일 등은
`git status` 할 때마다 항상 Untracked 파일이거나 혹은 Modified 상태가 되어
진짜 필요한 정보들을 보기 힘들어질 수도 있어요.
그 외에도 몇 가지 피드백을 더 드렸으니 한번 생각해보세요.
빠른 진행을 위해 Merge 하겠습니다!

2019-05-11 15:12 UTC, wotjd243 commented on bin/main/io/github/wotjd243/ecommerce/item/application/dto/ItemDto.kt
> +data class ItemRequestDto(
코틀린 데이터 클래스 👍

2019-05-11 15:12 UTC, wotjd243 commented on README.md
> +## 용어 사전
`Stock`이라는 것은 물품의 수량을 뜻할까요?

2019-05-11 15:12 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/ecommerce/item/domain/Item.java
> +        return new ItemResponseDto(detail.getTitle(), detail.getPrice(), detail.getGalleryUrl(), getStock(), itemState.name());
도메인 계층인 `Item`이 응용 계층인 `ItemResponseDto`를 의존하고 있네요. 만약 응용 계층의 요구 사항(표현 영역에서 받고자 하는 값의 형태 등)이 바뀐다면 도메인 계층도 그것에 영향을 받지 않을까요? 도메인 주도 설계의 핵심은 외부의 영향을 받지 않는 도메인 계층을 만드는 데에 있습니다.

2019-05-11 15:12 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/ecommerce/item/domain/ItemRepository.java
> +    List<Item> findAll(PagingDto paging);
마찬가지로 응용 계층의 영향을 받고 있네요.

2019-05-11 15:12 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/ecommerce/item/domain/Stock.java
> +        return this;
VALUE OBJECT는 불변이 보장되어야 하며 밸류 객체의 값을 변경하는 방법은 새로운 밸류 객체를 할당하는 것뿐입니다. 그렇다면 재고의 수량을 줄인 새로운 `Stock` VALUE OBJECT가 반환되어야 하지 않을까요?

2019-05-11 15:12 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/ecommerce/order/application/OrderService.java
> +    private boolean isPaid;
Spring Bean의 기본 Scope는 `singleton`이며, Singleton이 멀티 스레드 환경에서 서비스 형태로 사용되는 경우에는 상태 정보를 가지고 있지 않은 무상태(stateless) 방식으로 만들어져야 thread-safe 할 수 있습니다. 여러 클라이언트가 동시에 `isPaid`에 접근하여 값을 변경한다면 어떤 일이 발생할까요?

2019-05-11 15:12 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/ecommerce/order/domain/Order.java
> +    public OrderResponseDto toDto() {
도메인 계층에서 응용 계층으로 의존하는 코드입니다.

2019-05-11 15:12 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/ecommerce/order/domain/ShoppingBasket.java
> +        this.items = items;
컬렉션의 주솟값을 그대로 넘겨주게 되면 외부에 의한 변조가 일어나 불변성을 해칠 수 있어요. 새로운 컬렉션에 담아 외부에 의한 변조를 막는 것이 좋아 보여요.

2019-05-11 15:12 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/ecommerce/user/domain/ShippingAddresses.java
> +    private final Set<ShippingAddress> shippingAddresses;
일급 컬렉션 사용 👍

2019-05-11 15:12 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/ecommerce/user/domain/User.java
> +        return shippingAddresses.add(new ShippingAddress(address, zipCode));
`shippingAddresses`의 선언만 되었으며 할당은 되지 않아 `NullPointErexception`이 발생할 수 있습니다.

2019-05-11 15:12 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/ecommerce/user/domain/ZipCode.java
> +        private final String regex;
`String`을 패턴 매칭을 위해 `Pattern`으로 바꾸는 것은 꽤나 비싼 행위입니다. 미리 `Pattern`으로 만들어 사용하는 것은 어떨까요?

2019-05-11 15:12 UTC, wotjd243 commented on src/test/java/io/github/wotjd243/ecommerce/user/domain/ShippingAddressesTest.java
> +                ));
멋진 VALUE OBJECT와 일급 컬렉션 구현, 테스트 코드 작성입니다. 💯

2019-05-11 15:12 UTC, wotjd243 commented on src/test/java/io/github/wotjd243/ecommerce/order/domain/ShoppingBasketTest.java
> +        assertThat(basket.sumPrice()).isEqualTo(251.46);
다른 개발자가 이 테스트 코드를 본다면 '251.46'라는 숫자가 어떻게 나온 건지 알 수 있을까요? 테스트를 위해 주어진 상황을 조금 더 친절하게 설명하면 좋을 것 같아요.

2019-05-11 15:12 UTC, wotjd243 commented on README.md
> +- `Item`은 조회 시 가격순, 이름순으로 정렬을 할 수 있다.
현재까지 구현된 것을 모델링으로 표현해보는 것은 어떨까요?

2019-05-11 15:13 UTC, merged

2019-05-12 04:10 UTC, ivvve commented on README.md
> +## 용어 사전
Stock은 `재고`를 의미합니다.
용어사전에 업데이트가 필요하겠네요.

2019-05-12 04:13 UTC, ivvve commented on src/main/java/io/github/wotjd243/ecommerce/item/domain/Item.java
> +        return new ItemResponseDto(detail.getTitle(), detail.getPrice(), detail.getGalleryUrl(), getStock(), itemState.name());
좋은 지적 감사합니다.👍
해당 내용 적용하도록 하겠습니다