Release/step1
wotjd243/ddd-project pull request #13
Opened 2019-04-30 09:37 UTC by yanghun0070

요구사항 추가 및 도메인 객체 생성

2019-05-02 12:50 UTC, wotjd243 requested changes
추가적인 설계와 구현이 필요해 보입니다.
피드백 남겼으니 확인하고 개선할 부분 있으면 반영해 보세요.
코드 개선 시, 모델링도 함께 업데이트되어야 하는 점 잊지 마세요.

2019-05-02 12:50 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/shoppinggogo/cart/domain/Cart.java
> +        this.productList = productList;
서로 다른 AGGREGATE 간에 직접 참조할 때 발생할 수 있는 가장 큰 문제는 편리함을 오용할 수 있습니다. ID 참조를 사용하는 것은 어떨까요?

2019-05-02 12:50 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/shoppinggogo/product/domain/Product.java
> +    private int highestPrice;
`lowestPrice`와 `highestPrice`는 `Price`라는 VALUE OBJECT로 분리해보는 것은 어떨까요?

2019-05-07 13:24 UTC, yanghun0070 commented on src/main/java/io/github/wotjd243/shoppinggogo/product/domain/Product.java
> +    private int highestPrice;
넵, 강사님 말씀해주신데로 변경하였습니다 ^^;;
지금 저희가 오해를 하여, 지금 커밋 리뷰 댓글 수정중에 있네여 ㅠㅠ

2019-05-12 05:28 UTC, wotjd243 approved these changes
지난 리뷰 때보다 많은 기능이 구현되었네요. 👍 
하지만 아직 사용자가 장바구니에 담은 상품이 어느 쇼핑몰의 상품인지 구분 등의
구현되지 않은 요구 사항이 눈에 보이며, 도메인 계층에 대한 테스트 코드가 많이 빠져있습니다.
요구 사항을 테스트 코드로 작성해보면 혹시 빠진 구현이 없는지 확인할 수 있으며,
다른 개발자에게는 구현 코드에 대한 도메인 지식도 함께 제공해 줄 수 있습니다.
step2에 해당하는 내용은 따로 코멘트하지 않았으며, 몇 가지 생각거리는 따로 남겨두었으니 의논해보세요.
빠른 진행을 위해 Merge 하겠습니다!

2019-05-12 05:28 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/shoppinggogo/cart/domain/Cart.java
> +@Data
Lombok의 `@Data`는 `@ToString`, `@EqualsAndHashCode`, `@Getter`가 모든 멤버 변수에, `@Setter`는 모든 non-final 멤버 변수에 사용되며 `@RequiredArgsConstructor`가 사용되는 매우 강력한 어노테이션입니다. 아래의 링크를 참고하여 가급적 ENTITY에는 사용하지 않는 것을 추천합니다.
https://www.popit.kr/%EC%8B%A4%EB%AC%B4%EC%97%90%EC%84%9C-lombok-%EC%82%AC%EC%9A%A9%EB%B2%95

2019-05-12 05:28 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/shoppinggogo/cart/domain/Cart.java
> +    private List<Long> checkedProductIds; //체크되어진 제품 ID 목록
"체크된 제품 ID 목록"이라는 것은 요구 사항과 용어 사전, 모델링에서 알 수가 없네요. `Cart` 입장에서 "체크된 제품 ID 목록"이라는 것은 데이터베이스에 저장하고 관리해야 할 상태 값인가요? `matchByCheckedProductIds()`를 동작시키기 위한 용도라면 상태 값으로 안 가져도 될 것 같아요.

2019-05-12 05:28 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/shoppinggogo/cart/domain/Cart.java
> +    private List<Product> products; //제품 목록
이전 리뷰에서 코멘트를 남겼었습니다. 서로 다른 AGGREGATE 간에 직접 참조할 때 발생할 수 있는 가장 큰 문제는 편리함을 오용할 수 있습니다. ID 참조를 사용하는 것은 어떨까요?

2019-05-12 05:28 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/shoppinggogo/cart/infra/CartRepository.java
> +    public List<Product> selectProductsToCart(Long userId);
REPOSITORY가 AGGREGATE인 `Cart`를 조회해온 다음 `getProducts()`를 이용하는 것은 어떨까요? 도메인 주도 설계를 잠시 잊고 '우아한 코드'에 대해서 생각해보면 좋을 것 같아요.
https://youtu.be/MDZ8wUi-jzU

2019-05-12 05:28 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/shoppinggogo/payment/domain/Amount.java
> +    public static final int MINIMUM_NUMBER = 1;
매직넘버를 상수로 관리 👍

2019-05-12 05:28 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/shoppinggogo/payment/domain/Amount.java
> +    public static final int MAXIMUM_NUMBER = 100000000;
Java7부터는 `100_000_000`처럼 숫자에 underscore("_")를 사용하여 가독성을 높일 수 있습니다.

2019-05-12 05:28 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/shoppinggogo/payment/domain/Payment.java
> +        this.paymentDate = paymentDate;
혹시 Date 클래스의 위험성에 대해서 알고 계시나요? 아래의 글을 참고하여 외부에 의한 변조가 일어날 수 없도록 변경해보면 좋을 것 같아요.
https://d2.naver.com/helloworld/645609

2019-05-12 05:28 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/shoppinggogo/shipping/domain/GeneralBusinessNumber.java
> +        String ePattern = "^\\d{3}-\\d{2}-\\d{4}$";
매직넘버는 상수로 관리하는 것이 그 의미를 이해하는 데 도움이 될 것 같아요. 그리고 `String`을 패턴 매칭을 위해 `Pattern`으로 바꾸는 것은 꽤나 비싼 행위이므로 미리 `Pattern`으로 만들어 사용하는 것은 어떨까요?

2019-05-12 05:28 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/shoppinggogo/shipping/domain/GeneralEmail.java
> +        String ePattern = "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$";
마찬가지로 매직넘버는 상수로 관리하는 것이 그 의미를 이해하는 데 도움이 될 것 같아요.

2019-05-12 05:28 UTC, wotjd243 commented on README.md
> + 유저 엔
현재까지 구현된 것을 모델링으로 표현해보는 것은 어떨까요?

2019-05-12 05:28 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/shoppinggogo/user/ui/UserController.java
> +    UserService userService;
Spring에서 필드 주입을 권장하지 않는 이유가 무엇일까요?

1. 단일 책임의 원칙(Single Responsibility Principle)을 위반할 수 있다.
2. 의존성이 클래스 내부로 숨는다.
3. 인스턴스화가 어려워 테스트하기 어렵다.
4. final을 쓸 수 없어 불변성이 보장되지 않는다.

위의 이유로 스프링 공식 문서에서도 생성자 주입을 권장하고 있습니다.

2019-05-12 05:28 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/shoppinggogo/cart/domain/Cart.java
> +public class Cart {
"장바구니 목록에서 두 개 이상의 상품의 쇼핑몰이 같다면, 배송비는 무료로 배송된다.", "장바구니의 상품들의 쇼핑몰 이름 중복이 없다면, 상품 개별 2500원이 추가 결제된다."와 같은 요구 사항은 구현이 필요해 보입니다.

2019-05-12 05:28 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/shoppinggogo/order/domain/Order.java
> +        this.orderProducts = products;
새로운 리스트 컬렉션에 담아 외부에 의한 변조를 막는 것은 어떨까요?

2019-05-12 05:28 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/shoppinggogo/product/domain/Product.java
> +    private List<PriceRecord> prices;
`PriceRecord`가 컬렉션으로 관리되는 이유가 무엇일까요? 쇼핑몰마다 각각의 최저가와 최고가가 있다는 뜻인가요? 요구 사항과 용어 사전, 모델링을 보아도 알 수 없어 궁금하네요.

2019-05-12 05:28 UTC, wotjd243 commented on src/test/java/io/github/wotjd243/shoppinggogo/cart/domain/CartTest.java
> +public class CartTest {
중요한 AGGREGATE 중 하나인 `Cart`에 대한 테스트 코드가 빠져있네요. 테스트 코드를 작성해보면 어떨까요?

2019-05-12 05:28 UTC, merged

2019-05-12 05:44 UTC, yanghun0070 commented on src/main/java/io/github/wotjd243/shoppinggogo/cart/domain/Cart.java
> +@Data
넵, 수정하겠습니다. ^^~!

2019-05-12 05:48 UTC, yanghun0070 commented on src/main/java/io/github/wotjd243/shoppinggogo/cart/domain/Cart.java
> +    private List<Product> products; //제품 목록
넵, 저건 말씀하신데로 Id로 변경하였습니다. ~
다음 step2 에서 확인하실 수 있을꺼예요~!

2019-05-12 05:57 UTC, yanghun0070 commented on src/main/java/io/github/wotjd243/shoppinggogo/cart/domain/Cart.java
> +    private List<Long> checkedProductIds; //체크되어진 제품 ID 목록
이부분은 잘못되서 생긴 부분입니다~! 
지적 감사합니다 수정하였습니다.

2019-05-12 06:03 UTC, yanghun0070 commented on src/main/java/io/github/wotjd243/shoppinggogo/product/domain/Product.java
> +    private List<PriceRecord> prices;
넵,  용어사전, 모델링이 업데이트가 되지 않았네요.
초반에 목적은 `PriceRecord` **업체별 가격 기록**들을 목록을 API에서 확인할 수 있을 거라고 생각해서 구현했습니다.
네이버API 에서 제공해주지 않아서 다시 변경사항을 진행할 예정입니다~

2019-05-12 06:08 UTC, yanghun0070 commented on src/main/java/io/github/wotjd243/shoppinggogo/user/ui/UserController.java
> +    UserService userService;
이부분에 대해서는 잘 몰랐던 부분이네요.. ^^; :)

2019-05-12 06:10 UTC, yanghun0070 commented on src/test/java/io/github/wotjd243/shoppinggogo/cart/domain/CartTest.java
> +public class CartTest {
넵, 이부분 관련해서 다음 step2 에 진행 하겠습니다. ^^~!

2019-05-12 06:15 UTC, yanghun0070 commented on src/main/java/io/github/wotjd243/shoppinggogo/order/domain/Order.java
> +        this.orderProducts = products;
넵, 다음 step2 에 변경될 거예요~

2019-05-12 06:30 UTC, yanghun0070 commented on src/main/java/io/github/wotjd243/shoppinggogo/cart/infra/CartRepository.java
> +    public List<Product> selectProductsToCart(Long userId);
좋은 자료네요 감사합니다. :) 👍 👍 👍

2019-05-12 06:39 UTC, yangjeehan commented on src/main/java/io/github/wotjd243/shoppinggogo/payment/domain/Amount.java
> +    public static final int MAXIMUM_NUMBER = 100000000;
말씀하신대로 수정했습니다

2019-05-12 06:40 UTC, yangjeehan commented on src/main/java/io/github/wotjd243/shoppinggogo/payment/domain/Payment.java
> +        this.paymentDate = paymentDate;
Date 클래스에서 setMethod을 가지고 있어 문제가 발생할 수 있다는 점을 리마인드 했습니다 감사합니다

2019-05-12 06:52 UTC, yangjeehan commented on src/main/java/io/github/wotjd243/shoppinggogo/shipping/domain/GeneralBusinessNumber.java
> +        String ePattern = "^\\d{3}-\\d{2}-\\d{4}$";
말씀하신바가

2019-05-12 07:15 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/shoppinggogo/shipping/domain/GeneralBusinessNumber.java
> +        String ePattern = "^\\d{3}-\\d{2}-\\d{4}$";
👍