Release/step1
wotjd243/ddd-project pull request #14
Opened 2019-04-30 11:02 UTC by chldbtjd2272

2019-05-02 12:45 UTC, wotjd243 requested changes
`Buyer`와 `Seller` AGGREGATE를 따로 구현한 것이 좋았습니다. 💯 
요구 사항과 테스트 코드 또한 깔끔하게 구현해주셨습니다.
피드백 남겼으니 확인하고 개선할 부분 있으면 반영해 보세요.
코드 개선 시, 모델링도 함께 업데이트되어야 하는 점 잊지 마세요.

2019-05-02 12:45 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/aladin/book/domain/Author.java
> +public class Author {
VALUE OBJECT 👍

2019-05-02 12:45 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/aladin/common/Email.java
> +    private final static String EMAIL_PATTERN = "^(.+)@(.+)$";
`String`을 패턴 매칭을 위해 `Pattern`으로 바꾸는 것은 꽤나 비싼 행위입니다. 미리 `Pattern`으로 만들어 사용하는 것은 어떨까요?

2019-05-02 12:45 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/aladin/exception/AlreadyBoundException.java
> +public class AlreadyBoundException extends RuntimeException {
커스터마이징 한 예외 클래스 👍

2019-05-02 12:45 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/aladin/enrollment/domain/Enrollment.java
> +    private Long sellerId; // 보통 Seller 로 하는데 수업에서 일단 id로 하라고 하니...
서로 다른 AGGREGATE 간에는 ID를 이용한 참조 방식을 사용하면 복잡도를 낮추는 것과 함께 한 AGGREGATE에서 다른 AGGREGATE를 수정하는 문제를 원천적으로 방지할 수 있습니다. 👍

2019-05-02 12:45 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/aladin/registeredbook/domain/RegisteredBook.java
> +    private Enrollment enrollment;
양방향 탐색을 사용하는 이유가 있을까요? 탐색 방향을 부여하면 양방향 탐색에 비해 상호 의존성이 줄어들어 설계가 단순해지며, 추가적으로 도메인의 본질적인 방향성이 드러날 수 있을 것 같습니다.

2019-05-02 12:50 UTC, hojinDev commented on src/main/java/io/github/wotjd243/aladin/registeredbook/domain/RegisteredBook.java
> +    private Enrollment enrollment;
평소 jpa 만들던 습관이였습니다. 단방향으로 변경하도록 하겠습니다.

2019-05-05 06:34 UTC, wotjd243 approved these changes
벌써 표현 영역과 응용 영역의 일부를 작업하였고, 피드백까지 반영 잘 했네요. 👍 
아직 양방향 탐색을 하고 있는 곳이 남아 있어 코멘트를 달았으니 확인해보세요.
모델링도 함께 작업하면 좋을 것 같아요. Merge 하겠습니다.

2019-05-05 06:34 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/aladin/book/application/BookService.java
> +        return !ObjectUtils.isEmpty(getBook(id));
`Book`이 없는 경우, `IllegalArgumentException`이 발생하는 것을 올바르게 처리하는지 확인이 필요해 보여요.

2019-05-05 06:34 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/aladin/reservationbook/domain/ReservationBook.java
> +    public ReservationBook(ShoppingBasket shoppingBasket, RegisteredBook registeredBook) {
아직 서로 다른 AGGREGATE 간에 양방향 탐색을 하고 있으며, 만약 `ReservationBook`가 `ShoppingBasket`에 종속되었다면 `ShoppingBasket` AGGREGATE로 옮기는 것도 좋아 보이네요.

2019-05-05 06:34 UTC, merged