Release/step2
wotjd243/ddd-project pull request #22
Opened 2019-05-09 11:50 UTC by chldbtjd2272

2019-05-14 06:38 UTC, wotjd243 requested changes
스프링의 다양한 기능을 적절히 활용하여 코드 구현에 최선을 다해주셨어요. 👍  
자주 사용하는 코드에 대한 대응과 에러에 대한 대응 등을 통해
현재 업무에서 프로젝트를 어떻게 만들고 있는지 알 수 있었고, 저 또한 많은 생각을 할 수 있었어요.
같이 고민해보면 좋을 것 같은 의견을 남겨놓았으니 충분히 고민했으면 좋겠습니다.
아직 구현되지 않는 요구 사항 구현과 모델링도 부탁드릴게요!

2019-05-14 06:38 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/aladin/error/GlobalExceptionHandler.java
> +//    }
사용하지 않는 코드는 과감하게 제거하는 것이 좋겠네요. 👍

2019-05-14 06:38 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/aladin/common/dto/ApiResponse.java
> +public class ApiResponse {
현재 사용하지 않는 클래스인 것 같아요. 필요하지 않다면 제거 부탁드려요!

2019-05-14 06:38 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/aladin/response/ApiResponse.java
> +public class ApiResponse<T> {
`org.springframework.http.ResponseEntity`가 아닌 직접 `ApiResponse`를 만들어 사용하면 어떤 이점이 있을까요?

2019-05-14 06:38 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/aladin/reservation/application/ReservationService.java
> +            throw new MaxOverReservationException(String.format("최대 %s 권을 찜할 수 있습니다.", LIMIT_RESERVATION_COUNT));
"최대 15권의 책을 찜할 수 있다."라는 요구 사항의 구현은 응용 계층에서 하는 것이 좋을까요? 도메인 계층에서 하는 것이 좋을까요? 각각의 장단점에 대해서 같이 생각해봐요.

2019-05-14 06:38 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/aladin/exception/MaxOverReservationException.java
> +public class MaxOverReservationException extends BusinessException {
`MaxOverReservationException`와 같은 커스터마이징 한 예외 클래스가

- `exception`이라는 공통 패키지에 있는 것
- `reservation`이라는 패키지의 도메인 계층 혹은 응용 계층에 있는 것

중 어느 것이 유지 보수하기 좋을까요?

2019-05-14 06:38 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/aladin/book/domain/Book.java
>  import java.util.UUID;
`@NoArgsConstructor`의 `access` 설정이 필요하겠네요.

2019-05-14 06:38 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/aladin/enrollment/domain/Enrollment.java
>  @NoArgsConstructor(access = AccessLevel.PROTECTED)
`PRIVATE`이 아닌 `PROTECTED`인 의도가 궁금하네요. 혹시 알려주실 수 있을까요?

2019-05-14 06:38 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/aladin/common/domain/Address.java
> +package io.github.wotjd243.aladin.common.domain;
공통으로 쓰는 VALUE OBJECT는 한곳에 관리한다. 👍 "`User`와 `Buyer`, `Seller`는 공통으로 쓰는 VALUE OBJECT가 한 곳에 모인 `Person`이라는 클래스를 상속한다."라는 것에 대해서는 어떻게 생각하세요?

2019-05-14 06:38 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/aladin/enrollment/application/EnrollmentService.java
> +        Enrollment enrollment = enrollmentRequestDto.toEntity();
- `EnrollmentRequestDto` 내부에서 `Enrollment` AGGREGATE를 만드는 행위
- 응용 계층에서 `EnrollmentRequestDto`가 가진 값을 가져와(`get()`) `Enrollment` AGGREGATE를 만드는 행위

두 행위의 장단점에 대해서 같이 고민해보면 좋을 것 같은데 어떻게 생각하세요?

2019-05-14 06:38 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/aladin/enrollment/application/EnrollmentService.java
> +    public EnrollmentResponseDto save(EnrollmentRequestDto enrollmentRequestDto) {
아래 3개의 글을 읽고 같이 이야기해보면 좋겠어요. 현재 요구 사항 수준에서 `EnrollmentRequestDto`가 아닌 `Enrollment`를 직접 받으면 어떤 문제가 발생할까요?

- https://www.slipp.net/wiki/pages/viewpage.action?pageId=2031636
- https://www.slipp.net/questions/23
- https://www.slipp.net/questions/93

2019-05-14 06:38 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/aladin/enrollment/domain/Enrollment.java
>          for (long i = 0, length = count.getCount(); i < length; i++) {
VALUE OBJECT인 `Count`를 만든 만큼 적극적으로 써보면 어떨까요?

2019-05-14 06:38 UTC, wotjd243 commented on src/test/java/io/github/wotjd243/aladin/enrollment/EnrollmentTest.java
>      @Test
이미 `io.github.wotjd243.aladin.enrollment.domain.EnrollmentTest`가 중복으로 존재하니 삭제해도 되겠네요.

2019-05-14 06:38 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/aladin/enrollment/domain/RegisteredBook.java
> -        this.amount = amount;
이제 판매자가 등록한 책의 수량을 파악할 수 있는 기능이 `Enrollment`에 생기면 될까요?

2019-05-14 06:38 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/aladin/reservation/application/ReservationService.java
> +        return null;
구체적인 코드 구현을 기대하겠습니다. 👍

2019-05-14 06:38 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/aladin/reservation/domain/Reservation.java
> +        this.registeredBookId = registeredBookId;
저는 코드를 보며 `Enrollment` AGGREGATE의 `RegisteredBook` ENTITY `id`는 `Enrollment` ROOT ENTITY에 의존한다고 생각했었습니다. 그러나 `Reservation` AGGREGATE를 보며 '어쩌면 `RegisteredBook` ENTITY `id`는 독립된 식별자일 수도 있겠다.'라는 생각을 했어요. 만약 그렇다면 `RegisteredBook`은 별개의 AGGREGATE로 분리할 수 있다고 보는데 여기에 대해 어떻게 생각하시나요?

2019-05-14 06:38 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/aladin/reservation/ui/dto/ReservationDto.java
> +    public static class Create {
`ReservationDto` 내부에 `Create`가 있는 형태의 클래스 구조는 어떤 의도로 작성된 걸까요? 찜 기능 관련 DTO를 한곳에 모으기 위한 의도일까요? `EnrollmentRequestDto`와 `EnrollmentResponseDto` 등의 다른 DTO와는 또 다른 구조네요.

2019-05-14 06:38 UTC, wotjd243 commented on src/main/java/io/github/wotjd243/aladin/user/domain/User.java
> +    public static User createSeller(String loginId, String password, String name, String phoneNumber, String email) {
어떤 방식으로 사용자를 등록할 수 있고, 그 사용자는 다시 어떻게 구매자와 판매자로 나누어지는지 그 과정이 궁금하네요. README.md의 모델링에 그 과정을 표현해주시면 좋을 것 같아요. 👍

2019-05-14 12:16 UTC, hjlee83 commented on src/main/java/io/github/wotjd243/aladin/common/dto/ApiResponse.java
> +public class ApiResponse {
넵 옮겨서 만들었는데 기존것을 안지웠네요

2019-05-14 12:17 UTC, hjlee83 commented on src/main/java/io/github/wotjd243/aladin/response/ApiResponse.java
> +public class ApiResponse<T> {
에러 응답과 정상 응답을 동일시할때 사용하고 있습니다.

2019-05-14 12:18 UTC, hjlee83 commented on src/main/java/io/github/wotjd243/aladin/reservation/application/ReservationService.java
> +            throw new MaxOverReservationException(String.format("최대 %s 권을 찜할 수 있습니다.", LIMIT_RESERVATION_COUNT));
이게 초기 모델이라 변경되었습니다. 현재는 도메인 모델에 넣었습니다.

2019-05-14 12:20 UTC, hjlee83 commented on src/main/java/io/github/wotjd243/aladin/enrollment/domain/Enrollment.java
>  @NoArgsConstructor(access = AccessLevel.PROTECTED)
queryDsl fieldInjection 할때 안되서 하던 습관이 남아있었습니다. PRIVATE 로 변경해놓겠습니다.

2019-05-14 12:29 UTC, hjlee83 commented on src/main/java/io/github/wotjd243/aladin/reservation/ui/dto/ReservationDto.java
> +    public static class Create {
여러명이 분할해서 만들다보니 통일이 안되었습니다.
통일시키도록 하겠습니다.

의도는 
요청과 응답 dto 를 구분하면서
요청에 관련된 행위에 따라 dto를 분리한것입니다.

2019-05-16 12:57 UTC, hjlee83 commented on src/main/java/io/github/wotjd243/aladin/error/GlobalExceptionHandler.java
> +//    }
넵

2019-05-16 13:16 UTC, chldbtjd2272 commented on src/main/java/io/github/wotjd243/aladin/enrollment/domain/RegisteredBook.java
> -        this.amount = amount;
이건 구현했습니다!

2020-07-11 06:54 UTC, closed without merging